apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: amik7n3yp-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/amik7n3yp-dotnet-basic-gitops